"""
Django settings for DjangoProjectRoot project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from typing import List, Dict, Any
from django.utils.translation import gettext_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a8yi7uu4yq1*$r(7l-ugzft+xdk)j$znz-+ft2kff#cf9_s6&%'

# 安全警告：生产环境必须关闭 DEBUG！
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# 允许访问的域名（DEBUG=False 时需配置）
ALLOWED_HOSTS = [
    r'byronding.byron-audio.net',
]


# 注册的 Django 应用
# Application definition
INSTALLED_APPS = [
    # 管理员后台
    'django.contrib.admin',
    # 认证系统
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 静态文件处理
    'django.contrib.staticfiles',
    # 自定义应用
    # 过滤器
    'python_obj_filters.apps.PythonObjFiltersConfig',
    # 主页
    'home_page_app.apps.HomePageAppConfig',
    # 介绍
    'introduction_page_app.apps.IntroductionPageAppConfig',
    # 鸣谢
    'thanks_page_app.apps.ThanksPageAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # 新增多语支持
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoProjectRoot.urls'


TEMPLATES: List[Dict[str, Any]] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'dynamic_resources/',
        ],  # 模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProjectRoot.wsgi.application'


# 数据库配置（默认 SQLite）
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES: Dict[str, Dict[str, str]] = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGES = [
    ('en', gettext_lazy('English')),
    ('zh-hans', gettext_lazy('Simplified Chinese')),
]

LOCALE_PATHS = [
    Path.joinpath(BASE_DIR, 'locale'),
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True

USE_TZ = True

# 静态文件 URL（CSS/JS/图片）
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static_resources/'

STATICFILES_DIRS: List[Path] = [
    # 资源
    BASE_DIR / 'static_resources/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

